{{- if .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openvscode-server.fullname" . }}-env
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
{{- end }}
