apiVersion: v1
kind: Service
metadata:
  name: {{ include "openvscode-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "openvscode-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 3000
  selector:
    app.kubernetes.io/name: {{ include "openvscode-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
