{{- if .Values.configMap }}
{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openvscode-server.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openvscode-server.labels" . | nindent 4 }}
data:
  {{- with .Values.configMap.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
---
{{- if .Values.openvscode }}
{{- if .Values.openvscode.userSettings }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openvscode-server.fullname" . }}-user-settings
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openvscode-server.labels" . | nindent 4 }}
data:
  settings.json: |
    {{- .Values.openvscode.userSettings | nindent 4 }}
{{- end }}
{{- end }}
