{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "openvscode-server.fullname" . }}-pvc
  namespace: {{ include "openvscode-server.namespace" . }}
  labels:
    {{- include "openvscode-server.labels" . | nindent 4 }}
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.persistence.accessModes }}
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  {{- else }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- end }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- with .Values.persistence.selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
