apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openvscode-tenant-a
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:my-org/manifest.git
    targetRevision: main
    path: openvscode-server
    helm:
      valueFiles:
        - $values/values.yaml      # refers to second source below
  sources:
    - repoURL: git@github.com:my-org/manifest.git
      targetRevision: main
      path: openvscode-server
    - repoURL: git@github.com:my-org/platform.git
      targetRevision: main
      path: overlays/uat/tenantA/openvscode-server
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: tenant-a
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
